name: macOS

on: [push, pull_request]

jobs:
  build:

    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          brew update
          brew install swig
          python -m pip install --upgrade pip
          pip install poetry
          poetry install

      - name: Run unit tests
        run: poetry run pytest -v

      - name: Build
        run: poetry build

      - name: Install from tar.gz
        run: |
          pip install dist/*.tar.gz
          ykman --version
          [[ -z "$(ykman --version | grep -E "not found|missing")" ]]
          pip uninstall -y canokey-manager

      - name: Install from wheel
        run: |
          pip install dist/*.whl
          ykman --version
          [[ -z "$(ykman --version | grep -E "not found|missing")" ]]
          pip uninstall -y canokey-manager

      - name: PyInstaller
        run: |
          poetry run pyinstaller ykman.spec
          dist/ykman/ykman --version
          [[ -z "$(dist/ykman/ykman --version | grep -E "not found|missing")" ]]
          export REF=$(echo ${GITHUB_REF} | cut -d '/' -f 3)
          mv dist/ykman dist/ykman-$REF

      - name: Upload build
        uses: actions/upload-artifact@v1
        with:
          name: ykman-builds-macos
          path: dist
